{% set name = 'bob.ip.qualitymeasure' %}
{% set project_dir = environ.get('RECIPE_DIR') + '/..' %}

package:
  name: {{ name }}
  version: {{ environ.get('BOB_PACKAGE_VERSION', '0.0.1') }}

build:
  entry_points:
    - compute_qualityfeatures.py = bob.ip.qualitymeasure.script.compute_qualitymeasures:main
    - remove_highlights.py = bob.ip.qualitymeasure.script.remove_highlights:main
  number: {{ environ.get('BOB_BUILD_NUMBER', 0) }}
  run_exports:
    - {{ pin_subpackage(name) }}
  script:
    - cd {{ project_dir }}
    {% if environ.get('BUILD_EGG') %}
    - "{{ PYTHON }} setup.py sdist --formats=zip"
    {% endif %}
    - "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config {{ pkg_config }}
    - cmake {{ cmake }}
    - make {{ make }}
  host:
    - python {{ python }}
    - setuptools {{ setuptools }}
    - pip {{ pip }}
    - bob.extension
    - bob.blitz
    - bob.ip.base
    - bob.ip.color
    - libblitz {{ libblitz }}
    - numpy {{ numpy }}
    - scipy {{ scipy }}
  run:
    - python
    - setuptools
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('scipy') }}

test:
  imports:
    - {{ name }}
  commands:
    - nosetests --with-coverage --cover-package={{ name }} -sv {{ name }}
    - sphinx-build -aEW {{ project_dir }}/doc {{ project_dir }}/sphinx
    - sphinx-build -aEb doctest {{ project_dir }}/doc sphinx
    - conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    - conda inspect objects -p $PREFIX {{ name }}  # [osx]
  requires:
    - nose {{ nose }}
    - coverage {{ coverage }}
    - sphinx {{ sphinx }}
    - sphinx_rtd_theme {{ sphinx_rtd_theme }}
    - bob.io.base
    - bob.io.image
    - imageio {{ imageio }}
    - imageio-ffmpeg {{ imageio_ffmpeg }}

about:
  home: https://www.idiap.ch/software/bob/
  license: GNU General Public License v3 (GPLv3)
  summary: Image-quality feature-extractors for PAD applications
  license_family: GPL
